[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "nast-gs"
version = "0.1.0"
description = "NAST Geo Suite - satellite tracker"
authors = ["NAST"]
